### ISSUE TITLE
Pardot change API Auth process, need to switch the auth method to POST

### ISSUE THREAD

**Issue by crakage** [mneedham91/PyPardot4#23]
Hi Team, 

Pardot updated their authentication requirement and prevent the usage of GET.
https://github.com/mneedham91/PyPardot4/blob/master/pypardot/client.py

Could you update the authentication function in order to use POST request instead?

More info:  http://developer.pardot.com/#authentication

Kind regards
David

**Comment by mneedham91** [comment]
Hi David, thanks for pointing this out. My personal computer is actually in the shop but should be back from Dell in a few days. When I have that I'll take a stab at this. I'm always happy to accept pull requests from others, as well :)

**Comment by mneedham91** [comment]
@crakage Actually, I'm not sure if that's an issue. Check out lines 152-164 of client.py. This a POST request to login route. Everything looks fine to me. Am I missing something?

**Comment by crakage** [comment]
Hi Matt, Thanks for the update. Weird, I will check again tomorrow ( i am in Europe) and update you.

**Comment by crakage** [comment]
My bad I check the other wrapper: https://github.com/joshgeller/PyPardot/blob/master/pypardot/client.py posted the issue on the wrong Repository sorry for that

**Comment by mneedham91** [comment]
No problem. Thanks for keeping on eye on changes to the API!

**Comment by berntmelba** [comment]
The original description of this issue left out an important detail regarding supported Pardot API auth process that is relevant to this project.  As per notice on http://developer.pardot.com, passing credentials in querystring of any Pardot API request is now deprecated.  I see `requests.post()` calls in this project specifying `params=` instead of `data=` for passing parameters which results in parameters being passed in the query string of the URL instead of the body of the request.  Please update to pass parameters in the body of the POST request.
